# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3c7476560ed3572fd05d3e42b1446475c78deb783f557bf5d5ed5cfc445d0dd1de981be4389207926d57df87c4b1ac89f682099c2bb08461595de990c2c2c84c

test:
  secret_key_base: 9338f2f06b2008f39adb5631032e85912c4895412c6d0e7ccaf29ae7a974a2c407271010cdc0d6436d79fcc33f85e2a26bcc0536d016aa642300db074ea9d02a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
